spring:
  application:
    name: subpilot
  profiles:
    active: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /v3/api-docs
